=== AlvaroCalde/alvarocalperLMSGIProyectoLMSGI/examen/02/data/02.dtd
<!-- ===========================================
     DTD para tarjeta de visita
     Versión: 1.0
     =========================================== -->

<!-- ELEMENTO RAÍZ -->
<!ELEMENT tarjetaVisita (nombre,cargo,empresa,logo?,web?,redes?)>
     <!ATTLIST tarjetaVisita id ID #REQUIRED>
     <!ATTLIST tarjetaVisita version CDATA "1.0">
<!ATTLIST tarjetaVisita xmlns:xsi CDATA #IMPLIED
                xsi:noNamespaceSchemaLocation CDATA #IMPLIED>



<!-- ===========================================
     DATOS PRINCIPALES
     =========================================== -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT logo (#PCDATA)>
     <!ATTLIST logo formato (png|jpg|svg|webp) "png">
     <!ATTLIST logo descripcion CDATA #IMPLIED>




<!-- ===========================================
     INFO WEB Y REDES
     =========================================== -->
<!ELEMENT web (#PCDATA)>
<!ELEMENT redes (linkedin?,otro*)>
<!ELEMENT linkedin (#PCDATA)>
<!ELEMENT otro (#PCDATA)>
     <!ATTLIST otro tipo CDATA #REQUIRED>

=== AlvaroCalde/alvarocalperLMSGIProyectoLMSGI/examen/02/data/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tarjetaVisita SYSTEM "02.dtd">
<tarjetaVisita id="tv001" version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="02.xsd">
    <nombre>xxxxx</nombre>
    <cargo>xxxxxx</cargo>
    <empresa>xxxxxxx</empresa>
    <logo  formato="png" descripcion=""></logo>
    <web>

    </web>
    <redes>
        <linkedin></linkedin>
        <otro tipo="psa"></otro>
    </redes>

</tarjetaVisita>
