=== AlvaroCalde/alvarocalperLMSGIProyectoLMSGI/ut4/02/02.dtd
<!ELEMENT mail (remitente,destinatarios,fechamensaje,asunto?,mensaje,ficheros_adjuntos*)>
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatarios (destinatario+)>
<!ELEMENT fechamensaje (dia,mes,año)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT mensaje (p | h2 | ul)*>
<!ELEMENT ficheros_adjuntos (fichero+)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT p (#PCDATA | strong)*>
<!ELEMENT h2 (#PCDATA | strong)*>
<!ELEMENT ul (li+)>
<!ELEMENT fichero (nombre+,tipo+)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT li (#PCDATA | strong)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>

=== AlvaroCalde/alvarocalperLMSGIProyectoLMSGI/ut4/02/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mail SYSTEM "02.dtd">
<mail>
    <remitente>peper@gmail.com</remitente>
    <destinatarios>
        <destinatario>maria@gmail.com</destinatario>
        <destinatario>sofia@gmail.com</destinatario>
    </destinatarios>
    <fechamensaje>
        <dia>25</dia>
        <mes>11</mes>
        <año>2024</año>
    </fechamensaje>
    <asunto>Cena Navidad 2024</asunto>
    <mensaje>
        <p>
            Invitación a la Cena de Navidad
        </p>
        <p> 
            Querido/a <strong>compañero/a</strong> : 
        </p>
        <p> Nos complace invitarle a compartir una noche especial en nuestra <strong/> Cena de
            Navidad<strong/>, que se celebrará en el encantador <strong>Parador de Benavente</strong>. 
        </p>
        <h2>
            <strong>Detalles del Evento:</strong>
        </h2>
        <ul>
            <li>
                <strong>Fecha:</strong> Jueves, 21 de diciembre de 2023 
            </li>
            <li>
                <strong>Hora:</strong> 21:00 
            </li>
            <li>
                <strong>Lugar:</strong> Parador de Benavente
            </li>
        </ul>
        <p>
            Ven a disfrutar de una velada inolvidable llena de buena compañía, deliciosa gastronomía
            y el espíritu navideño que tanto nos une. Habremos preparado un menú especial pensado
            para celebrar este mágica ocasión.
        </p>
        <p>
            <strong>Por favor, confirma tu asistencia antes del 15 de diciembre de 2023</strong>
            respondiendo a este correo o contactando al <strong>[teléfono/email de contacto]</strong>
        </p>
        <p>
            Esperamos conytar contigo para hacer de esta cena un momento añun más especial. ¡No faltes!
        </p>
        <p>Con cariño</p>
        <p>Director</p>
    </mensaje>
    <ficheros_adjuntos>
        <fichero>
            <nombre>documento.pdf</nombre>
            <tipo>application/pdf</tipo>
        </fichero>
        <fichero>
            <nombre>imagen.png</nombre>
            <tipo>image/png</tipo>
        </fichero>
    </ficheros_adjuntos>
</mail>
