=== AlvaroCalde/alvarocalperLMSGIProyectoLMSGI/ut4/05/05.dtd
<<<<<<< HEAD
<!ELEMENT estudiantes (estudiante+)>
<!ATTLIST estudiantes xmlns:xsi CDATA #IMPLIED
                xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ATTLIST estudiante idest ID #REQUIRED
                    tutor1 IDREF #IMPLIED
                    tutor2 IDREF #IMPLIED>
<!ELEMENT estudiante (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
=======
<!ELEMENT grupo (estudiante+)>
<!ATTLIST estudiante idest ID #REQUIRED
                    tutor1 IDREF #IMPLIED
                    tutor2 IDREF #IMPLIED>
<!ELEMENT estudiante (#PCDATA)>
>>>>>>> 03ef643c807d157a3d0b1189b483273674c9bb55

=== AlvaroCalde/alvarocalperLMSGIProyectoLMSGI/ut4/05/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE estudiantes SYSTEM "05.dtd">
<estudiantes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="05.xsd">
    <estudiante idest="E1">
        <nombre>Daniel</nombre>
        <apellidos>Carvajal</apellidos>
    </estudiante>
    <estudiante idest="E2" tutor1="E1">
        <nombre>Javier</nombre>
        <apellidos>Ontiveros</apellidos>
    </estudiante>
    <estudiante idest="E3" tutor1="E1" tutor2="E2">
        <nombre>Isi</nombre>
        <apellidos>Palazón</apellidos>
    </estudiante>
</estudiantes>
